# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceb8d3ef1c111e5079be538ec3abdb021bf0c8d90641d8d762908c1f724335181747e324c98d6b379bbca5dc145cc7a64cedae24883e31f25fd663658b34d468

test:
  secret_key_base: 21de37c98dc2c33f2a9cf0ac7a6f35f874fc90e38e7fcd75129534fa199996b69877cd795ca743c29a6f863b70b654ada65cfb638dee29cb835b910e4bf621ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
